### ISSUE TITLE
任意键继续后，提示找不到文件

### ISSUE THREAD

**Issue by AlmondLG** [yuwenhuisama/LibrePatch-FFXIVQuickLauncherCN#1]
![1](https://github.com/yuwenhuisama/LibrePatch-FFXIVQuickLauncherCN/assets/79155429/e6eb60bf-2ce2-4a05-9662-7a81567c03af)
win11系统 已经管理员运行，报错如图

**Comment by yuwenhuisama** [comment]
`bin` 文件夹里面有 `LIbrePatch.exe` 这个文件么？

**Comment by AlmondLG** [comment]
有

**Comment by AlmondLG** [comment]
是不是系统问题呢？win11无法使用？

**Comment by yuwenhuisama** [comment]
你装一下.net core试试， [.net core ](https://dotnet.microsoft.com/zh-cn/download)

或者你可以手动把`Config.json` 拷贝进`bin` 文件夹然后手动启动 `LibrePatch.exe`试试。

**Comment by moondryad** [comment]
确保安装net后仍然存在，直接启动exe会因为无法读取到config，提示用默认，然后报错后自动结束进程

**Comment by moondryad** [comment]
cmd管理员启动会改目录。。。。。以及linux和win的地址/\不一样。。。改了之后V1正常运行了

**Comment by yuwenhuisama** [comment]
看样子是bat的问题，我后面改成powershell的脚本吧

**Comment by AlmondLG** [comment]
额，大佬后续有更新么- =release好像没更新了哇

**Comment by yuwenhuisama** [comment]
@AlmondLG 更新了1.2.1，现在改成用Powershell脚本启动程序了。
